/*
 * host_command.h
 *
 *  Created on: Mar 7, 2025
 *      Author: Mike
 */

#ifndef INC_HOST_COMMAND_H_
#define INC_HOST_COMMAND_H_

#define HOST_COMMAND_VERSION 0
#define HOST_COMMAND_ECHO 1
#define HOST_COMMAND_GET_GPIO_MODE 2
#define HOST_COMMAND_READ_GPIOS 3
#define HOST_COMMAND_SET_GPIO 4
#define HOST_COMMAND_READ_ENCODERS 5
#define HOST_COMMAND_GET_STATUS 6
#define HOST_COMMAND_SET_STEPPER_ACTIVE_RAMPUP_PULSE_WIDTH 7
#define HOST_COMMAND_SET_STEPPER_ACTIVE_CRUISE_PULSE_WIDTH 8
#define HOST_COMMAND_SET_STEPPER_ACTIVE_RAMPDOWN_PULSE_WIDTH 9
#define HOST_COMMAND_SET_STEPPER_CONTROLS 10
#define HOST_COMMAND_SET_STEPPER_ENABLE 11
#define HOST_COMMAND_SET_STEPPER_FORWARD 12
#define HOST_COMMAND_START_STEPPER_HOME_POSITIONING 13
#define HOST_COMMAND_RUN_STEPPER 14


#endif /* INC_HOST_COMMAND_H_ */
